import sqlite3
cno=sqlite3.connect('myDatabase.db')
print("Database Created")
cno.execute('''create table employee(code varchar not null,name varchar not null,salary number null);''')
print("Table Created")
cno.execute("insert into employee(code,name,salary) values('S2101','Micheal',1000001)")
cno.execute("insert into employee(code,name,salary) values('S2102','Abdul',1000002)")
print("Data Inserted")
cno.commit()
crs=cno.execute("select * from employee")
print("--------------------------------------")
print("Original Data:- \n")
for rs in crs:
    print("Employee Id:",rs[0])
    print("Employee Name:",rs[1])
    print("Employee Salary:",rs[2],"\n")
print("---------------------------------------")
cno.execute("delete from employee WHERE code = 'S2101'")
cno.execute("update employee set salary = '1000000' where code = 'S2102'")
crs=cno.execute("select * from employee")
print("Data After Updating  & Deleting:- \n")
for rs in crs:
    print("Employee Id:",rs[0])
    print("Employee Name:",rs[1])
    print("Employee Salary:",rs[2],"\n")